export const VariantType = {
  DEFAULT: "default",
  PRIMARY: "primary",
  SECONDARY: "secondary",
  SUCCESS: "success",
  ACCENT: "accent",
  DANGER: "danger",
  WARNING: "warning",
  INFO: "info",
  DARK: "dark",
  LIGHT: "light",
  ROUND: "round",
  OUTLINE: "outline",
  BIG: "big",
  SMALL: "small",
  BLOCK: "block",
};
